### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by Shifulor** [clitic/kdam#2]
Hey, i just now discovered this project and must say it looks very peomising. I am coming from an indicatif background and must say that kdam seems superior is some aspects. However i have a few questions:

1. Does kdam support async? Especially tokio (I am working on an asynchronous download function and this was not really possible with indicatif since MultiBar could not work properly in a Multithread enviroment.
2. Can i color the bars themselves? While the progress design is quite nice i do not like only having black and white.

**Comment by clitic** [comment]
## About Tokio

kdam doesn't provide an async API. Tokio runtimes can use synchronous API. See [example](https://github.com/clitic/kdam/blob/main/examples/file_download/src/main.rs).

## About Multiple Bars And Multi-threading

kdam takes a different approach from indicatif for printing multiple bars. indicatif uses `MultiBar` on the other hand kdam uses absolute positioning method. When `update` method is called kdam acquires a global static lock from [lock](https://docs.rs/kdam/latest/kdam/lock/index.html) module, prints the progress bar and releases the lock. There is also one caveat of this approach that on completion cursor is always restored to its original position.

Progress bars could be printed at different positions in the terminal by specifying `position`. Progress bars on multiple threads also work fine. See [example](https://github.com/clitic/kdam/blob/main/examples/bar_multi_thread.rs).

Text can be also printed at a specific position using `eprint_at!` macro. See [example](https://github.com/clitic/kdam/blob/main/examples/msg_between.rs).

## About Colours

Currently, only animated portion of bar could be coloured. This is because the original tqdm has such a thing when using `colour` argument. See [example](https://github.com/clitic/kdam/blob/main/examples/misc_coloured.rs).

In the future kdam will support bar templating and colours can be applied to individual components. Meanwhile `RichProgress` can be an alternative. See [example](https://github.com/clitic/kdam/blob/main/examples/bar_rich.rs).

**Comment by Shifulor** [comment]
Many thanks for the detailed explaination, kdam sound amazing.
I assume the only reason its relatively unpopular is because of indicatifs fame?
I would love to move to kdam with our projects, however i see a little issue arising: You say that your only dependency is "terminal-size". However terminal-size seams to not support *BSD. Does this affect kdam? Have there ben any BSD tests? Many thanks in advance

**Comment by clitic** [comment]
No tests have been made for BSD. But kdam should work on BSD because teminal-size uses [rustix](https://github.com/bytecodealliance/rustix) which are bindings to POSIX-ish APIs and rustix eventually supports [BSD](https://github.com/bytecodealliance/rustix/search?q=freebsd&type=).
