### ISSUE TITLE
Wrapping an iterator doesn't work

### ISSUE THREAD

**Issue by oersted** [clitic/kdam#4]
This simple pattern doesn't work properly on 0.2.3
```
use kdam::prelude::*;
for _ in tqdm!(iter) {}
```

The timer does update on every iteration, but the progress bar doesn't tick up, it stays at zero with inf ETA and ?it/s.

This works as it should though:
```
use kdam::prelude::*;
let mut pb = tqdm!(total = vec.len());
for _ in vec.iter() {
    pb.update(1);
}
```

Tangential note: I suggest that `.refresh()` should be automatically called as soon as the tqdm is created. Otherwise, nothing is displayed until the first call to `.update()`.

**Comment by clitic** [comment]
![Screenshot_20220829-192831_Termux](https://user-images.githubusercontent.com/71246790/187218659-d64eea5f-63de-4adb-8086-365c734b84f3.jpg)

This bug is fixed and released to crates.io as [v0.2.4](https://crates.io/crates/kdam/versions)

 @oersted For patterns like `tqdm!(iter)` `.refresh` method is called only once when the first value of iterable is used. If you want continuous output from kdam then use `force_refresh = true` inside the macro. Also, the timer is started when bar is created. For other patterns like `tqdm!` macro `.refresh` method is not called.

**Comment by oersted** [comment]
Awesome! That was fast, thanks.
